### ISSUE TITLE
The Preview panel is layered on top, hiding other windows

### ISSUE THREAD

**Issue by ronmurp** [madskristensen/MarkdownEditor2022#69] opened 2022-08-16 08:50 UTC
When the markdown editor is open, showing the editing and preview panels, the preview panel remains in the foreground when another window is opened over the markdown editor.

**To Reproduce**
- Open the markdown editor, pinned, in a 'New Horizontal Document Group', showing both edit and preview panels.
- Open the Output window, unpinned, so that it overlays the editing windows.
See image.

**Expected behavior**
The output window should overlay the editor panels.

**Screenshots**
![image](https://user-images.githubusercontent.com/686210/184838543-021bb870-fcfb-4be1-82f7-571d4363b1dc.png)

**Comment by madskristensen** [comment] 2022-08-19 17:31
Duplicate of #62

**Closed** 2022-08-19 17:31 UTC
Labels: bug
