### ISSUE TITLE
Preview window stays in the foreground

### ISSUE THREAD

**Issue by cjahermanns** [madskristensen/MarkdownEditor2022#62] opened 2022-07-22 07:58 UTC
**Describe the bug**
When a markdown file is open, the preview window stays in the foreground when a side panel window is opened (properties or test explorer docked on the side with auto hide enabled).

**To Reproduce**
1. Open a markdown file with preview
2. Open one of the docked and auto hidden side panel windows
3. The preview stays on top of the side panel window

**Expected behavior**
I would expect the preview window gets pushed back (as the markdown file window does)

**Comment by cjahermanns** [comment] 2022-07-22 12:13
Probably same as / related to #49

**Comment by madskristensen** [comment] 2022-07-22 15:09
Yes, this is a dupe of #49. Closing this one

**Closed by madskristensen** 2022-07-22 15:09 UTC
Labels: bug
